switch to abundance quantification in python
NBISweden/ancient-microbiome-smk pull request #69
Opened 2022-05-31 08:38 UTC by clami66

Here, we introduce a simple python script to count occurrences of taxids from one text file in a gzipped sam file. Tests look good, but we can't be absolutely sure that they are correct since the code in the original pipeline contains bugs

Fixes #68

2022-09-05 09:26 UTC, clami66 commented
Tests now pass @percyfal

2022-09-07 07:07 UTC, percyfal requested changes
I assume the empty foo file got added by mistake? Remove it and then we can merge.

2022-09-07 12:31 UTC, clami66 commented
> I assume the empty foo file got added by mistake? Remove it and then we can merge.

it was obviously integral to the inner workings of the pipeline... but now I have removed it :)

2022-09-07 12:46 UTC, percyfal approved these changes

2022-09-07 12:46 UTC, merged